# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: 'echo "CWD: ${PWD}"; cat ${PWD}/.npmrc; echo "end"'
    #workingDirectory: # Optional
    #failOnStderr: false # Optional

#- task: npmAuthenticate@0
#  inputs:
#    customEndpoint: npm_repos
#    workingFile: ./.npmrc

- task: CmdLine@2
  inputs:
    azureSubscription: 'npm_repos'
    script: 'echo "CWD: ${PWD}"; cat ${PWD}/.npmrc; echo "end"'
    #workingDirectory: # Optional
    #failOnStderr: false # Optional

- task: CmdLine@2
  inputs:
    azureSubscription: 'npm_repos'
    script: 'git checkout master'
    #workingDirectory: # Optional
    #failOnStderr: false # Optional

#- script: |
#    git checkout master
#    npm run prepenv
#    npm run build
#  displayName: 'npm prepenv/build'

- task: Npm@1
  inputs:
    command: 'custom'
    #workingDir: # Optional
    verbose: false # Optional
    customCommand: run prepenv
    customRegistry: 'useNpmrc' # Optional. Options: useNpmrc, useFeed
    #customFeed: # Required when customRegistry == UseFeed
    customEndpoint: npm_repos # Optional
    #publishRegistry: 'useExternalRegistry' # Optional. Options: useExternalRegistry, useFeed
    #publishFeed: # Required when publishRegistry == UseFeed
    #publishPackageMetadata: true # Optional
    #publishEndpoint: # Required when publishRegistry == UseExternalRegistry

- task: Npm@2
  inputs:
    command: 'custom'
    #workingDir: # Optional
    verbose: false # Optional
    customCommand: run build
    customRegistry: 'useNpmrc' # Optional. Options: useNpmrc, useFeed
    #customFeed: # Required when customRegistry == UseFeed
    customEndpoint: npm_repos # Optional
    #publishRegistry: 'useExternalRegistry' # Optional. Options: useExternalRegistry, useFeed
    #publishFeed: # Required when publishRegistry == UseFeed
    #publishPackageMetadata: true # Optional
    #publishEndpoint: # Required when publishRegistry == UseExternalRegistry

- task: Npm@3
  inputs:
    command: 'custom'
    #workingDir: # Optional
    verbose: false # Optional
    customCommand: run customPublish
    customRegistry: 'useNpmrc' # Optional. Options: useNpmrc, useFeed
    #customFeed: # Required when customRegistry == UseFeed
    customEndpoint: npm_repos # Optional
    #publishRegistry: 'useExternalRegistry' # Optional. Options: useExternalRegistry, useFeed
    #publishFeed: # Required when publishRegistry == UseFeed
    #publishPackageMetadata: true # Optional
    #publishEndpoint: # Required when publishRegistry == UseExternalRegistry
